stages:
  - build-libopenshot-audio
  - trigger-libopenshot

linux-builder:
  stage: build-libopenshot-audio
  artifacts:
    expire_in: 4 weeks
    paths:
    - build/install-x64/*
  script:
    - mkdir -p build; cd build;
    - cmake -D"CMAKE_INSTALL_PREFIX:PATH=install-x64" -D"CMAKE_BUILD_TYPE:STRING=Release" ../
    - make
    - make install
  when: always
  tags:
    - linux

mac-builder:
  stage: build-libopenshot-audio
  artifacts:
    expire_in: 4 weeks
    paths:
    - build/install-x64/*
  script:
    - mkdir -p build; cd build;
    - cmake -D"CMAKE_INSTALL_PREFIX:PATH=install-x64" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -D"CMAKE_BUILD_TYPE:STRING=Release" -D"CMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk" -D"CMAKE_OSX_DEPLOYMENT_TARGET=10.9" ../
    - make
    - make install
  when: always
  tags:
    - mac

windows-builder-x86:
  stage: build-libopenshot-audio
  artifacts:
    expire_in: 4 weeks
    paths:
    - build\install-x86\*
  script:
    - $env:LIBOPENSHOT_AUDIO_DIR = "C:\msys32\usr"
    - $env:UNITTEST_DIR = "C:\msys32\usr"
    - $env:ZMQDIR = "C:\msys32\usr"
    - $env:Path = "C:\msys32\mingw32\bin;C:\msys32\mingw32\lib;C:\msys32\usr\lib\cmake\UnitTest++;C:\msys32\home\jonathan\depot_tools;C:\msys32\usr;C:\msys32\usr\lib;" + $env:Path;
    - New-Item -ItemType Directory -Force -Path build
    - cd build
    - cmake -D"CMAKE_INSTALL_PREFIX:PATH=install-x86" -G "MinGW Makefiles" -D"CMAKE_BUILD_TYPE:STRING=Release" ../
    - mingw32-make
    - mingw32-make install
  when: always
  tags:
    - windows

windows-builder-x64:
  stage: build-libopenshot-audio
  artifacts:
    expire_in: 4 weeks
    paths:
    - build\install-x64\*
  script:
    - $env:LIBOPENSHOT_AUDIO_DIR = "C:\msys64\usr"
    - $env:UNITTEST_DIR = "C:\msys64\usr"
    - $env:ZMQDIR = "C:\msys64\usr"
    - $env:Path = "C:\msys64\mingw64\bin;C:\msys64\mingw64\lib;C:\msys64\usr\lib\cmake\UnitTest++;C:\msys64\home\jonathan\depot_tools;C:\msys64\usr;C:\msys64\usr\lib;" + $env:Path;
    - New-Item -ItemType Directory -Force -Path build
    - cd build
    - cmake -D"CMAKE_INSTALL_PREFIX:PATH=install-x64" -G "MinGW Makefiles" -D"CMAKE_BUILD_TYPE:STRING=Release" ../
    - mingw32-make
    - mingw32-make install
  when: always
  tags:
    - windows

trigger-pipeline:
  stage: trigger-libopenshot
  script:
    - "curl -X POST -F token=$LIBOPENSHOT_PIPELINE_TOKEN -F ref=master http://gitlab.openshot.org/api/v4/projects/1/trigger/pipeline"
  when: always
  dependencies: []
  tags:
    - linux
